const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const ALL_PACKAGES = [
  {
    id: 'pkg-kashmir-classic',
    name: 'Spiti Valley Traverse',
    price: 22900,
    originalPrice: 29500,
    duration: '6 Days / 5 Nights',
    durationDays: 6,
    rating: 5.0,
    ratingCount: 450,
    hotelStars: '4★ Premium Stays',
    hotelClass: '4',
    route: 'Manali → Kaza → Chandratal → Manali',
    routeList: ['Manali', 'Kaza', 'Chandratal'],
    description: 'Explore high altitude Spiti villages, post cards from Hikkim, and camp under the stars at Chandratal.',
    inclusions: ['flights', 'hotel', 'transfers', 'meals', 'sightseeing'],
    highlights: [
      'Drive through Atal Tunnel & Kunzum Pass',
      'Visit the ancient Key & Dhankar monasteries',
      'Chandratal lake camping and stargazing',
      'Explore Langza, Hikkim & Komik villages'
    ],
    image: '/travel-leh-6.jpg',
    themes: ['Mountain', 'Romantic', 'Adventure'],
    destination: 'Kashmir',
    detailsAvailable: true,
    link: '/travel/srinagar-to-leh',
    category: 'Road Trip',
    difficulty: 'Moderate',
    groupType: 'Curated group Trip',
    nextDeparture: 'Aug, 2026',
    startPoint: 'Manali',
    isBestSeller: true,
    showOnHome: true,
  },
  {
    id: 'pkg-kashmir-gulmarg',
    name: 'Gulmarg Skiing',
    price: 26900,
    originalPrice: 32000,
    duration: '7 Days / 6 Nights',
    durationDays: 7,
    rating: 4.9,
    ratingCount: 312,
    hotelStars: '5★ Luxury Chalet',
    hotelClass: '5',
    route: 'Srinagar → Gulmarg → Srinagar',
    routeList: ['Srinagar', 'Gulmarg Chalet', 'Srinagar Houseboat'],
    description: 'Ascend Asia\'s highest cable car to ski Apharwat Peak with expert coaching and cozy chalets.',
    inclusions: ['flights', 'hotel', 'transfers', 'meals', 'sightseeing'],
    highlights: [
      'Certified ski instruction on pristine powder slopes',
      'Phase 1 & 2 Gondola tickets to Apharwat Peak summit',
      'Apres-ski steam therapy, sauna & traditional Wazwan feast'
    ],
    image: 'https://images.unsplash.com/photo-1615966650071-855b15f29ad1?auto=format&fit=crop&w=800&q=80',
    themes: ['Mountain', 'Adventure'],
    destination: 'Kashmir',
    detailsAvailable: true,
    link: '/travel/package/pkg-kashmir-gulmarg',
    category: 'Camping',
    difficulty: 'Challenging',
    groupType: 'Curated group Trip',
    nextDeparture: 'Aug, 2026',
    startPoint: 'Srinagar',
    showOnHome: false,
  },
  {
    id: 'pkg-kerala-4in1',
    name: 'Kerala Couple Spl',
    price: 24999,
    originalPrice: 39999,
    duration: '5 Days / 4 Nights',
    durationDays: 5,
    rating: 4.8,
    ratingCount: 142,
    hotelStars: '3★ / 4★ Premium',
    hotelClass: '4',
    route: 'Kochi → Munnar → Thekkady → Alleppey → Kochi',
    routeList: ['Kochi', 'Munnar', 'Thekkady', 'Alleppey'],
    description: 'A curated couple & family getaway exploring Munnar hills, Periyar wildlife, and Alleppey backwaters.',
    inclusions: ['hotel', 'transfers', 'meals', 'sightseeing'],
    highlights: [
      'Private AC Sedan transport with friendly driver',
      'Premium hotel stays in Munnar & Thekkady',
      'Houseboat Stay with all meals in Alleppey backwaters',
      'Spice plantation guided walk'
    ],
    image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
    themes: ['Romantic', 'Beach', 'Heritage'],
    destination: 'Kerala',
    detailsAvailable: true,
    link: '/travel/package/pkg-kerala-4in1',
    category: 'Road Trip',
    difficulty: 'Easy',
    groupType: 'Private Tour',
    nextDeparture: 'Aug, 2026',
    startPoint: 'Kochi',
    isBestSeller: true,
    showOnHome: false,
  },
  {
    id: 'pkg-kerala-classic3',
    name: 'Kerala Classic Tour',
    price: 19999,
    originalPrice: 29999,
    duration: '4 Days / 3 Nights',
    durationDays: 4,
    rating: 4.7,
    ratingCount: 98,
    hotelStars: '3★ Standard',
    hotelClass: '3',
    route: 'Kochi → Munnar → Alleppey → Kochi',
    routeList: ['Kochi', 'Munnar', 'Alleppey'],
    description: 'Classic 3-night private getaway covering Munnar hills and Alleppey houseboats.',
    inclusions: ['hotel', 'transfers', 'meals', 'sightseeing'],
    highlights: [
      'Private transport in AC sedan with local driver',
      'Munnar tea garden sightseeing and mist valleys',
      'Alleppey private houseboat stay with onboard dining'
    ],
    image: 'https://images.unsplash.com/photo-1517462964-21fdcec3f25b?auto=format&fit=crop&w=800&q=80',
    themes: ['Romantic', 'Beach'],
    destination: 'Kerala',
    detailsAvailable: true,
    link: '/travel/package/pkg-kerala-classic3',
    category: 'Weekend',
    difficulty: 'Easy',
    groupType: 'Private Tour',
    nextDeparture: 'Aug, 2026',
    startPoint: 'Kochi',
    showOnHome: true,
  },
  {
    id: 'pkg-kerala-highlights',
    name: 'Kerala Highlights',
    price: 29999,
    originalPrice: 39999,
    duration: '6 Days / 5 Nights',
    durationDays: 6,
    rating: 4.9,
    ratingCount: 186,
    hotelStars: '4★ Premium',
    hotelClass: '4',
    route: 'Kochi → Munnar → Thekkady → Alleppey → Kochi',
    routeList: ['Kochi', 'Munnar', 'Thekkady', 'Alleppey'],
    description: 'Comprehensive 6-day highlight tour of Kerala\'s tea estates and backwater houseboats.',
    inclusions: ['hotel', 'transfers', 'meals', 'sightseeing'],
    highlights: [
      'Premium accommodations with breakfast included',
      'Private AC SUV for transfers and tours',
      'Guided spice plantation walk in Thekkady',
      'Heritage tour of colonial Fort Kochi'
    ],
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80',
    themes: ['Romantic', 'Adventure', 'Heritage'],
    destination: 'Kerala',
    detailsAvailable: true,
    link: '/travel/package/pkg-kerala-highlights',
    category: 'Road Trip',
    difficulty: 'Easy',
    groupType: 'Private Tour',
    nextDeparture: 'Aug, 2026',
    startPoint: 'Kochi',
  },
  {
    id: 'pkg-kerala-vibe',
    name: 'Kerala Vibe Special',
    price: 24999,
    originalPrice: 39999,
    duration: '5 Days / 4 Nights',
    durationDays: 5,
    rating: 4.8,
    ratingCount: 112,
    hotelStars: '3★ / 4★ Premium',
    hotelClass: '4',
    route: 'Thiruvananthapuram → Kovalam → Varkala → Alleppey',
    routeList: ['Thiruvananthapuram', 'Kovalam', 'Varkala', 'Alleppey'],
    description: 'Soak in southern vibes starting from Kovalam and Varkala beaches to the backwaters of Alleppey.',
    inclusions: ['hotel', 'transfers', 'meals'],
    highlights: [
      'Beachfront resort stays in Kovalam & Varkala',
      'Trivandrum heritage sightseeing tour',
      'Alleppey backwaters day cruise with lunch'
    ],
    image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
    themes: ['Romantic', 'Beach'],
    destination: 'Kerala',
    detailsAvailable: true,
    link: '/travel/package/pkg-kerala-vibe',
    category: 'Weekend',
    difficulty: 'Easy',
    groupType: 'Private Tour',
    nextDeparture: 'Aug, 2026',
    startPoint: 'Trivandrum',
  },
  {
    id: 'pkg-goa-beach',
    name: 'Goa Beach Escape',
    price: 12500,
    originalPrice: 17500,
    duration: '5 Days / 4 Nights',
    durationDays: 5,
    rating: 4.7,
    ratingCount: 220,
    hotelStars: '3★ Beachside Resort',
    hotelClass: '3',
    route: 'Panaji → Candolim Beach (2N) → Palolem Beach (2N)',
    routeList: ['Panaji Heritage Walk', 'Candolim Beach (2N)', 'Palolem Beach (2N)'],
    description: 'A curated getaway exploring heritage churches and the beautiful beaches of Goa.',
    inclusions: ['hotel', 'transfers', 'meals'],
    highlights: [
      'Historical Latin Quarter (Fontainhas) guided walking tour',
      'Scuba diving & snorkeling lesson at Grand Island',
      'Lakeside sunset drinks & traditional Goan fish curry cooking class'
    ],
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    themes: ['Beach', 'Adventure'],
    destination: 'Goa',
    detailsAvailable: true,
    link: '/travel/package/pkg-goa-beach',
    category: 'Weekend',
    difficulty: 'Easy',
    groupType: 'Curated group Trip',
    nextDeparture: 'Sep, 2026',
    startPoint: 'Panaji',
  },
  {
    id: 'pkg-rajasthan-royal',
    name: 'Rajasthan Royal Tour',
    price: 21500,
    originalPrice: 28000,
    duration: '8 Days / 7 Nights',
    durationDays: 8,
    rating: 4.9,
    ratingCount: 198,
    hotelStars: '5★ Royal Heritage Palace',
    hotelClass: '5',
    route: 'Jaipur (2N) → Jodhpur (2N) → Jaisalmer Camp (3N)',
    routeList: ['Jaipur Palace (2N)', 'Jodhpur Blue City (2N)', 'Jaisalmer Camp (3N)'],
    description: 'Experience majestic forts in Jaipur and Udaipur, and enjoy sunset desert camel safaris.',
    inclusions: ['hotel', 'transfers', 'meals', 'sightseeing'],
    highlights: [
      'Private heritage palace stays & luxury desert glamping',
      'Guided Amber Fort tour & camel sunset desert safari',
      'Stargazing dinner over the Thar desert dunes with Rajasthani folk music'
    ],
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
    themes: ['Heritage', 'Romantic'],
    destination: 'Rajasthan',
    detailsAvailable: true,
    link: '/travel/package/pkg-rajasthan-royal',
    category: 'Road Trip',
    difficulty: 'Easy',
    groupType: 'Curated group Trip',
    nextDeparture: 'Oct, 2026',
    startPoint: 'Jaipur',
    showOnHome: false,
  },
  {
    id: 'pkg-himachal-trek',
    name: 'Manali Valley Trek',
    price: 15900,
    originalPrice: 21000,
    duration: '6 Days / 5 Nights',
    durationDays: 6,
    rating: 4.8,
    ratingCount: 184,
    hotelStars: '4★ Riverview Resort',
    hotelClass: '4',
    route: 'Delhi → Shimla (2N) → Manali (3N) → Delhi',
    routeList: ['Shimla Heritage (2N)', 'Manali River View (3N)'],
    description: 'Escape to snowy peaks. Hike scenic mountain trails and enjoy paragliding in Solang Valley.',
    inclusions: ['hotel', 'transfers', 'meals'],
    highlights: [
      'Riverside cottage stays with snowy balcony views',
      'Paragliding at Solang Valley & Rohtang Pass excursion',
      'Guided cedar forest trek and hot sulfur spring bath in Vashisht'
    ],
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80',
    themes: ['Mountain', 'Adventure'],
    destination: 'Himachal',
    detailsAvailable: true,
    link: '/travel/package/pkg-himachal-trek',
    category: 'Trek',
    difficulty: 'Moderate',
    groupType: 'Curated group Trip',
    nextDeparture: 'Aug, 2026',
    startPoint: 'Manali',
    showOnHome: true,
  },
  {
    id: 'pkg-andaman-island',
    name: 'Andaman Island Getaway',
    price: 28900,
    originalPrice: 36500,
    duration: '6 Days / 5 Nights',
    durationDays: 6,
    rating: 4.9,
    ratingCount: 156,
    hotelStars: '5★ Beach Resort',
    hotelClass: '5',
    route: 'Port Blair (1N) → Havelock Island (3N) → Neil Island (1N)',
    routeList: ['Port Blair (1N)', 'Havelock Island (3N)', 'Neil Island (1N)'],
    description: 'Swim in turquoise waters of Radhanagar Beach and snorkel at Elephant Beach.',
    inclusions: ['hotel', 'transfers', 'meals', 'sightseeing'],
    highlights: [
      'Premium beachfront villa stay with private deck access',
      'Snorkeling at Elephant Beach & scuba dive lesson in Havelock',
      'Private cruise ferry transfers between islands'
    ],
    image: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80',
    themes: ['Beach', 'Adventure', 'Romantic'],
    destination: 'Andaman',
    detailsAvailable: true,
    link: '/travel/package/pkg-andaman-island',
    category: 'Weekend',
    difficulty: 'Easy',
    groupType: 'Private Tour',
    nextDeparture: 'Nov, 2026',
    startPoint: 'Port Blair',
  }
];

async function main() {
  console.log('Seeding initial data into MongoDB Atlas...');

  // 1. Seed Test Admin User
  const adminUser = await prisma.user.upsert({
    where: { email: 'admin@gobanjara.com' },
    update: {},
    create: {
      email: 'admin@gobanjara.com',
      name: 'Go Banjara Admin',
      phone: '9876543210',
      passwordHash: '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', // 'admin123'
      role: 'ADMIN',
    },
  });
  console.log('Admin User Seeded:', adminUser.email);

  // 2. Seed Sample Product
  const sampleProduct = await prisma.product.create({
    data: {
      name: 'Banjara Explorer Leather Backpack',
      description: 'Handcrafted premium leather backpack designed for wanderlust travelers.',
      price: 2499.00,
      image: '/fur_jaden_backpack.jpg',
      category: 'Travel Bags',
      rating: 4.9,
      inStock: true,
    },
  });
  console.log('Sample Product Seeded:', sampleProduct.name);

  // 3. Seed Travel Packages into TravelPackage collection
  for (const pkg of ALL_PACKAGES) {
    const { id, ...updateData } = pkg;
    const savedPkg = await prisma.travelPackage.upsert({
      where: { id: pkg.id },
      update: updateData,
      create: pkg,
    });
    console.log('Travel Package Seeded:', savedPkg.name, `(${savedPkg.id})`);
  }

  // 4. Update CatalogState
  await prisma.catalogState.upsert({
    where: { id: 'global_catalog' },
    update: { packages: ALL_PACKAGES },
    create: {
      id: 'global_catalog',
      packages: ALL_PACKAGES,
    },
  });
  console.log('CatalogState updated with all 10 travel packages.');

  console.log('MongoDB Atlas seeding complete! All 10 travel packages seeded.');
}

main()
  .catch((e) => {
    console.error('Seeding Error:', e);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
